UniqeNursery/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

admin.site.site_header = "UNIQUE NURSERY ADMIN"
admin.site.site_title = "UNIQUE NURSERY ADMIN PORTAL"
admin.site.index_title = "UNIQUE NURSERY"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nursery.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nursery/urls.py
from django.urls import path
from nursery import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('product/', views.product, name='product'),
    path('blog/', views.blog, name='blog'),
    path('product/productdetail/<int:myid><str:type>', views.productdetails, name='productdetail'),
    path('blog/readblog/<int:myid><str:type>', views.readblog, name='readblog'),
    path('addproduct', views.addproduct, name='addproduct'),
    path('writeblog/', views.writeblog, name='writeblog'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('order/', views.orders, name='order'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('changepassword/', views.changepassword, name='changepassword'),
]

nursery/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField


# Create your models here.
class ContactUs(models.Model):
    Full_Name = models.CharField(max_length=50)
    Email = models.EmailField(max_length=150)
    Mobile = models.CharField(max_length=20)
    Message = models.TextField(max_length=150)

    def __str__(self):
        return str(self.Full_Name) + ' send mail using ' + str(self.Email)


class UserDetails(models.Model):
    gender = {
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    }
    Profile_Pic = CloudinaryField('Profile_Pic', folder='nursery/User_Profile_Pics/', use_filename=True,
                                  unique_filename=False)
    User = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    Name = models.CharField(max_length=70)
    Date = models.DateField(auto_now=True, )
    Gender = models.CharField(max_length=50, choices=gender)
    Email = models.EmailField(max_length=254)
    Mobile = models.CharField(max_length=20)
    Facebook = models.URLField(max_length=300, blank=True)
    Twitter = models.URLField(max_length=300, blank=True)
    Instagram = models.URLField(max_length=300, blank=True)
    Website = models.URLField(max_length=300, blank=True)
    Pincode = models.CharField(max_length=10)
    Address = models.TextField(blank=True)

    def __str__(self):
        return str(self.User)


class ProductDetail(models.Model):
    planttype = {
        ('Flowering Plant', 'Flowering Plant'),
        ('Harbal Plant', 'Harbal Plant'),
        ('Indoor Plant', 'Indoor Plant'),
        ('Outdoor Plant', 'Outdoor Plant'),
        ('Air Purifier Plant', 'Air Purifier Plant'),
        ('Low Mantenance Plant', 'Low Mantenance Plant')
    }
    Product_Name = models.CharField(max_length=150)
    Plant_Type = models.CharField(max_length=50, choices=planttype)
    Real_Price = models.CharField(max_length=100)
    Discount_Price = models.CharField(max_length=100, blank=True)
    Description = models.TextField()
    Light = models.CharField(max_length=100)
    Watering = models.CharField(max_length=100)
    Where_To_Grow = models.CharField(max_length=100)
    Maintenance = models.CharField(max_length=100)
    Special_Feature = models.CharField(max_length=100)
    Product_Img = CloudinaryField('Product_Img', folder='nursery/Product_Images/', use_filename=True,
                                  unique_filename=False)
    Second_Img = CloudinaryField('Second_Img', folder='nursery/Product_Second_Image/', use_filename=True,
                                 unique_filename=False)

    def __str__(self):
        return str(self.Product_Name)


class Blogs(models.Model):
    planttype = {
        ('Flowering Plant', 'Flowering Plant'),
        ('Harbal Plant', 'Harbal Plant'),
        ('Indoor Plant', 'Indoor Plant'),
        ('Outdoor Plant', 'Outdoor Plant'),
        ('Air Purifier Plant', 'Air Purifier Plant'),
        ('Low Mantenance Plant', 'Low Mantenance Plant')
    }
    Blog_Name = models.CharField(max_length=150)
    Author = models.CharField(max_length=100)
    Date = models.DateTimeField(auto_now=True)
    Plant_Type = models.CharField(max_length=50, choices=planttype)
    Small_Info = models.TextField()
    Light = models.CharField(max_length=100)
    Watering = models.CharField(max_length=100)
    Where_To_Grow = models.CharField(max_length=100)
    Maintenance = models.CharField(max_length=100)
    Special_Feature = models.CharField(max_length=100)
    Main_Img = CloudinaryField('Main_Img', folder='nursery/Blog_Images/', use_filename=True, unique_filename=False)
    Second_Img = CloudinaryField('Second_Img', folder='nursery/Blog_Second_Image/', use_filename=True,
                                 unique_filename=False)
    Plant_Essentials = RichTextField(blank=True, null=True)
    Common_Problems = RichTextField(blank=True, null=True)
    Style_and_Decor = RichTextField(blank=True, null=True)

    def __str__(self):
        detail = f'{self.Blog_Name} wrote by {self.Author}'
        return str(detail)


class AddToCart(models.Model):
    Buyer = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
    Product = models.ForeignKey(ProductDetail, on_delete=models.CASCADE)
    Product_Amount = models.IntegerField()
    Product_Quantity = models.IntegerField()

    def __str__(self):
        order = f'{str(self.Buyer)} Add To Cart {str(self.Product)}'
        return order


class Order(models.Model):
    Buyer = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
    Product = models.ForeignKey(ProductDetail, on_delete=models.CASCADE)
    Order_Date = models.DateTimeField(auto_now=True)
    Product_Amount = models.IntegerField()
    Product_Quantity = models.IntegerField()
    Deliver = models.BooleanField(default=False)
    Order_Cancel_Position = models.BooleanField(default=False)

    def __str__(self):
        order = f'{str(self.Buyer)} Buy {str(self.Product)}'
        return order

    @property
    def showAddress(self):
        full_address = f'Address - {self.Buyer.Address} \nPincode - {self.Buyer.Pincode}'
        return full_address

nursery/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from nursery.models import ContactUs, UserDetails, ProductDetail, AddToCart, Order, Blogs
from nursery.forms import ContactForm, RegistrationForm, UserDetailsForm, AdminProfileForm, WriteBlogForm
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from django.core.mail import EmailMessage
from django.template.loader import get_template

# Create your views here.

"""
For Sending Html Email It Needed Argument 
Subject
Sender Email
Recevier Email In List 
Replay Email
Html Template Path
Context Is A Dictionary That Use In Html Template

"""


def html_email_Sanding(subject, html_template_path, reciver_emails, context_dict, sender_email=settings.EMAIL_HOST_USER,
                       replay_email=settings.EMAIL_HOST_USER):
    email_html_template = get_template(html_template_path).render(context_dict)
    email_message = EmailMessage(
        subject,
        email_html_template,
        sender_email,
        reciver_emails,
        reply_to=[sender_email]
    )
    email_message.content_subtype = 'html'
    yes = email_message.send(fail_silently=True)
    if yes == 0:
        return False
    else:
        return True


'''
Home Page Carry Resent Added Four Blogs And Products
'''


def home(request):
    blog = Blogs.objects.all().order_by('-pk')[:4]
    product = ProductDetail.objects.all().order_by('-pk')[:4]
    return render(request, 'nursery/home.html', {'allpr': product, 'allbl': blog})


"""
It's Only Show About Our Project.
"""


def about(request):
    return render(request, 'nursery/about.html')


"""
Contact Page Get FeedBack For Both Unknown Or Known User They Can Send Mail Through Fill This Form.

By Mistake User Enter Wrong Email That's Why We Ask Mobile Number For Backup.  
"""


# contact form page
def contact(request):
    if request.method == 'POST':
        confm = ContactForm(request.POST)
        if confm.is_valid():
            name = confm.cleaned_data['Full_Name']
            email = confm.cleaned_data['Email']
            mobile = confm.cleaned_data['Mobile']
            message = confm.cleaned_data['Message']
            contacts = ContactUs(Full_Name=name, Email=email, Mobile=mobile, Message=message)
            subject = "Contact with me " + name
            html_template_path = 'email/contact_email.html'
            content_html = {
                'today': datetime.now(),
                'mobile': mobile,
                'email': email,
                'name': name
            }
            html_email_Sanding(subject=subject, html_template_path=html_template_path, reciver_emails=[email],
                               context_dict=content_html)
            messages.success(request, 'Your Message Sended To Uniqe Nursery.')
            contacts.save()
        else:
            messages.error(request, 'Please Fill Again')
            confm = ContactForm()
        return render(request, 'nursery/contact.html', {'confm': confm})
    else:
        confm = ContactForm()
        return render(request, 'nursery/contact.html', {'confm': confm})


"""
Here We Fetch Data Form The DataBase (Blogs,ProductDetail) And Filter By There Plant Type For Showing Differnet Type Of Blogs And Products Respectivly On blog.html and product.html .
"""


def product(request):
    allProds = []
    catProds = ProductDetail.objects.values('Plant_Type', 'id')
    cats = {item['Plant_Type'] for item in catProds}
    for cat in cats:
        prod = ProductDetail.objects.filter(Plant_Type=cat)
        allProds.append(prod)

    parms = {'products': allProds}
    return render(request, 'nursery/product.html', parms)


def blog(request):
    allProds = []
    catProds = Blogs.objects.values('Plant_Type', 'id')
    cats = {item['Plant_Type'] for item in catProds}
    for cat in cats:
        prod = Blogs.objects.filter(Plant_Type=cat)
        allProds.append(prod)

    parms = {'products': allProds}
    return render(request, 'nursery/blog.html', parms)


"""
Here We Fetch That Data From The DataBase That Requested By User To All details Inside In.

That Two Functions Give Us Only Single Row From Their Respective Models Class.

If "productdetails" Function Get POST Request Form The Frontend It Will Collect All Data From That Page And Save To AddToCart Model Through Requested User This POST Request Work Only For Register User Unknown User Can't Be Add Item In The AddToCart Model .
"""


def productdetails(request, myid, type):
    prod = []
    product = ProductDetail.objects.filter(id=myid)
    catProds = ProductDetail.objects.filter(Plant_Type=type)
    prod.append(catProds)
    print(product[0].Product_Name)
    if request.method == 'POST':
        if product[0].Discount_Price == "":
            item_price = product[0].Real_Price
        else:
            item_price = product[0].Discount_Price
        quantity = request.POST['quantity']
        item_price = int(item_price) * int(quantity)
        atc = AddToCart(
            Buyer=request.user.userdetails,
            Product=product[0],
            Product_Amount=item_price,
            Product_Quantity=quantity
        )
        atc.save()
        messages.success(request, f"{product[0].Product_Name} Is Added In Your Cart.")
        return redirect('/addtocart/')
    return render(request, 'nursery/productdetail.html', {'product': product[0], 'prod': prod})


def readblog(request, myid, type):
    blog = Blogs.objects.filter(id=myid, Plant_Type=type)
    return render(request, 'nursery/readblog.html', {'blog': blog[0]})


"""
Order or Add to cart process writen here
"""


@login_required(login_url='/login/')
def addtocart(request):
    cart = AddToCart.objects.filter(Buyer=request.user.userdetails)
    if request.method == "POST":
        if 'Order' in request.POST:
            buyer = request.user.userdetails
            product_id = request.POST['prid'].split(',')[0]
            quantity = request.POST['quantity']
            price = request.POST['price']
            product = ProductDetail.objects.filter(id=product_id)
            if request.user.userdetails.Address == " ":
                messages.error(request, "First Fill Your Personal Details In Your Profile.")
            else:
                od = Order(
                    Buyer=buyer,
                    Product=product[0],
                    Product_Quantity=quantity[10:],
                    Product_Amount=price[2:],
                )
                od.save()
                messages.success(request, "Your Order Placed.\n Pay After Delivery.\n Prepaid Not Available.")
                messages.warning(request, "Check Mail For Order Detail\n If Mail Not Recive Change Your Mail")
                # Html Template Email Sending Process
                to = request.user.userdetails.Email
                address = request.user.userdetails.Address
                pincode = request.user.userdetails.Pincode
                mobile = request.user.userdetails.Mobile
                name = product[0].Product_Name
                img = product[0].Second_Img.url
                plant_type = product[0].Plant_Type
                subject = f'{name} - Order Placed'
                html_template_path = 'email/order_email.html'
                content_html = {
                    'product_name': name,
                    'address': f" Delivery - {address} , {pincode}",
                    'quantity': quantity,
                    'real': product[0].Real_Price,
                    'down': product[0].Discount_Price,
                    'price': price,
                    'mobile': f'Your Contact - {mobile}',
                    'img': img,
                    'plant_type': plant_type,
                    'pos': "Shipped",
                    'word': "View",
                    'view': f"""https://uniqenursery.herokuapp.com/product/productdetail/{product_id}{plant_type}"""
                }
                html_email_Sanding(subject=subject, html_template_path=html_template_path, reciver_emails=[to],
                                   context_dict=content_html)
                product_id = request.POST['prid'].split(',')[1]
                addcart = AddToCart.objects.get(id=product_id)
                addcart.delete()
                return redirect('/order')
        elif 'Remove' in request.POST:
            product_id = request.POST['prid'].split(',')[1]
            addcart = AddToCart.objects.get(id=product_id)
            addcart.delete()
            messages.success(request, "Item Removed From Your Cart.")
    return render(request, 'nursery/addtocart.html', {'added': cart})


@login_required(login_url='/login/')
def orders(request):
    orders = Order.objects.filter(Buyer=request.user.userdetails)
    if request.method == "POST":
        product_id = request.POST['prid']
        ord = Order.objects.get(id=product_id)
        ord.Order_Cancel_Position = True
        ord.save()
        messages.success(request, "Order Canceled Successfuly.")
        # Html Template Email Sending Process
        to = request.user.userdetails.Email
        address = request.user.userdetails.Address
        pincode = request.user.userdetails.Pincode
        mobile = request.user.userdetails.Mobile
        name = orders[0].Product.Product_Name
        img = orders[0].Product.Second_Img.url
        plant_type = orders[0].Product.Plant_Type
        subject = f'{name} - Order Canceled'
        html_template_path = 'email/order_email.html'
        content_html = {

nursery/templates/nursery/about.html
{% extends 'nursery/index.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/about.css' %} ">
{% endblock css %}

{% block title %}About{% endblock title %}
{% block body %}

<section class="aboutsection" style="--img:url('{% static 'nursery/IMAGE/back.jpg' %}')">
    <div class="infocontact">
        <h1>ABOUT UNIQE NURSERY</h1>
        <p>We firmly believe that we do not inherit the earth from our ancestors.</p>
    </div>
    <div class="aboutbox">
        <h1>WHO WE ARE</h1>
        <p>
            We are garden gnomes. Really!! We grow things, from dirt. <br>
            We don’t just sell plants, we make your gardens thrive and solve all your gardening issues, magically.
        </p>
        <div class="about">
            <div class="box">
                <img src="{% static 'nursery/IMAGE/rose.jpg' %} " alt="">
                <span class="title">Our History</span>
                <p class="content">
                    Lorem ipsum, dolor sit Lorem ipsum dolor sit amet consectetur adipisicing. amet consectetur
                    adipisicing elit. Repellendus ea ratione ullam veritatis ipsam odio aliquam voluptates atque
                    corrupti maxime!
                </p>
            </div>
            <div class="box">
                <img src="{% static 'nursery/IMAGE/what_we_do.png' %} " alt="">
                <span class="title">What We Do</span>
                <p class="content">
                    We create green spaces, both indoors and outdoors. We are here to make the concrete jungle, we call
                    home, a greener and more sustainable space through customized gardening solutions. Through our Own
                    Grown Farms initiative we convert open urban spaces into food gardens to lower food miles and
                    promote community gardening values.
                </p>
            </div>
            <div class="box">
                <img src="{% static 'nursery/IMAGE/how_we_do_it.png' %} " alt="">
                <span class="title">How We Do It</span>
                <p class="content">
                    We are driven by our passion to promote sustainability as a feasible way of life. We are devoted to
                    cultivating a community of gardeners who are as passionate about gardening as we are and hand
                    holding those who are not yet fully convinced, to dive deep into the green world with us.
                </p>
            </div>
            <div class="box">
                <img src="{% static 'nursery/IMAGE/our_mission.jpg' %} " alt="">
                <span class="title">Our Mission</span>
                <p class="content">
                    We have big dreams - for everyone.

                    Fully sustainable food farms on every inch of empty unused urban real estate, pan India dispatch
                    centres and nurseries that deliver plants to every home in every pin code, and a family of customers
                    who are more family than customer. We aim to make growing our own food a norm to reduce the carbon
                    footprint we generate and in the process neutralize environmental carbon percentage further.
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock body %}

nursery/templates/nursery/blog.html
{% extends 'nursery/index.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/blog.css' %} ">
{% endblock css %}


{% block title %}Blogs{% endblock title %}
{% block body %}

<section class="blogsection">
    <!-- Slider main container -->
    {% for i in products %}
    <div class="headtitle" id="{{i.0.Plant_Type}}">
        <h1>{{i.0.Plant_Type}}</h1>
    </div>
    <div class="swiper mySwiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
            <div class="swiper-slide box" onclick="location.href='readblog/{{i.0.id}}{{i.0.Plant_Type}}';" style="cursor: pointer;">
                <img src="{{i.0.Main_Img.url}}" alt="">
                <p class="title">{{i.0.Blog_Name}}</p>
                <p class="content">
                    {{i.0.Small_Info}}
                </p>
                <a href="readblog/{{i.0.id}}{{i.0.Plant_Type}}">Read More</a>
            </div>
            {% for j in i|slice:"1:" %}
            <div class="swiper-slide box" onclick="location.href='readblog/{{j.id}}{{j.Plant_Type}}';" style="cursor: pointer;">
                <img src="{{j.Main_Img.url}}" alt="">
                <span class="title">{{j.Blog_Name}}</span>
                <p class="content">
                    {{j.Small_Info}}
                </p>
                <a href="readblog/{{j.id}}{{j.Plant_Type}}">Read More</a>
            </div>
            {% endfor %}
        </div>
        <!-- If we need pagination -->
        <div class="swiper-pagination"></div>

        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

        <!-- If we need scrollbar -->
    </div>
    {% endfor %}
</section>

{% endblock body %}

{% block js %}
<script src="{% static 'nursery/JS/blog.js' %} "></script>
{% endblock js %}

nursery/templates/nursery/changepassword.html
{% extends "nursery/index.html" %}

{% block title %}Change Password{% endblock title %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/passwordchange.css' %}">

{% endblock css %}

{% block body %}
<section class="passwordchange" style="--imgb: url('{% static 'nursery/IMAGE/lrfc.jpg' %}');">
    <div class="contantbx">
        <div class="formbx">
            <h2>Password Change</h2>
            <form action="" method="post">
                {% csrf_token %}
                {% for fm in chpass %}
                <div class="inputbx">
                    <span class="placeholder">{{fm.label_tag}}</span>
                    <label for="">
                        {{fm}}
                    </label>
                </div>
                {% endfor %}
                <div class="inputbx">
                    <input type="submit" value="Forgot Password">
                </div>
                <div class="inputbx">
                    <p>Don't have an account? <a href="{% url 'registration' %}">Sign Up</a></p>
                    <p>Already have a account? <a href="{% url 'login' %}">Sign In</a></p>
                    <p class="center"><a href="{% url 'forgotpassword' %}">Forgot Password</a></p>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock body %}

nursery/templates/nursery/contact.html
{% extends 'nursery/index.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/contact.css' %} ">
{% endblock css %}

{% block title %}Contact{% endblock title %}
{% block body %}

<section class="contactsection" style="--img:url('{% static 'nursery/IMAGE/back.jpg' %}')">
    <div class="infocontact">
        <h1>CONTACT US ABOUT UNIQE NURSERY</h1>
        <p>Let's pass it on cleaner, better, and greener.</p>
    </div>
    <div class="contactbox">
        <div class="detailbox">
            <div class="box">
                <a href=""><i class="fa fa-phone-alt"></i></a>
                <div class="text">
                    <h3>Call as directly at</h3>
                    <p>+91-7999317168</p>
                </div>
            </div>
            <div class="box">
                <a href=""><i class="fa fa-envelope"></i></a>
                <div class="text">
                    <h3>Email</h3>
                    <p>dgmarket11@gmail.com</p>
                </div>
            </div>
            <div class="box">
                <a href=""><i class="fa fa-map-marker"></i></a>
                <div class="text">
                    <h3>Address</h3>
                    <p>Pratappura, Burhanpur M.P. <br>450331</p>
                </div>
            </div>
        </div>
        <div class="contactform">
            <h2>Contact For More Details</h2>
            <form class="form" action="{% url 'contact' %}" method="POST">
                {% csrf_token %}
                {% for form in confm %}
                <label for="">
                    <span class="label">{{form.label}}</span>
                    {{form}}
                </label><br>
                {% endfor %}
                <label for="">
                    <input type="reset" value="Reset">
                    <input type="submit" value="Send">
                </label>
            </form>
        </div>
    </div>
</section>

{% endblock body %}

nursery/templates/nursery/forgotpassword.html
{% extends "nursery/index.html" %}

{% block title %}Fogot Password{% endblock title %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/forgotpassword.css' %}">
{% endblock css %}

{% block body %}
<section class="forgotpw" style="--imgb: url('{% static 'nursery/IMAGE/lrfc.jpg' %}');">
    <div class="contantbx">
        <div class="formbx">
            <h2>Forgot Password</h2>
            <form action="" method="post">
                {% csrf_token %}
                {% for fm in fgpass %}
                <div class="inputbx">
                    <span class="placeholder">{{fm.label_tag}}</span>
                    <label for="">
                        {{fm}}
                    </label>
                </div>
                {% endfor %}
                <div class="inputbx">
                    <input type="submit" value="Forgot Password">
                </div>
                <div class="inputbx">
                    <p>Don't have an account? <a href="{% url 'registration' %}">Sign Up</a></p>
                    <p>Already have a account? <a href="{% url 'login' %}">Sign In</a></p>
                    <p class="center"><a href="{% url 'changepassword' %}">Password Change</a></p>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock body %}

nursery/templates/nursery/profile.html
{% extends 'nursery/index.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'nursery/CSS/profile.css' %}">
<style>
    label>a {
        display: none;
    }
</style>
{% endblock css %}

{% block title %}Profile{% endblock title %}
{% block body %}

<section class="profilesection">
    <div class="block">
        <div class="imgbox">
            {% if not request.user.userdetails.Profile_Pic %}
            <img src="{% static 'nursery/IMAGE/rose.jpg' %}" alt="hello">
            {% else %}
            <img src="{{request.user.userdetails.Profile_Pic.url}}" alt="Upload Your Image or Load Your Image">
            {% endif %}
        </div>
        <div class="sociallink">
            <ul>
                {% if not request.user.userdetails.Facebook %}
                <li><a href="https://www.facebook.com/" target="_blank" id="fb"><i class="fab fa-facebook-f"></i></a>
                </li>
                {% else %}
                <li><a href="{{request.user.userdetails.Facebook}}" target="_blank" id="fb"><i
                            class="fab fa-facebook-f"></i></a></li>
                {% endif %}
                {% if not request.user.userdetails.Twitter %}
                <li><a href="https://www.twitter.com/" target="_blank" id="twit"><i class="fab fa-twitter"></i></a></li>
                {% else %}
                <li><a href="{{request.user.userdetails.Twitter}}" target="_blank" id="twit"><i
                            class="fab fa-twitter"></i></a></li>
                {% endif %}
                {% if not request.user.userdetails.Instagram %}
                <li><a href="https://www.instagram.com/" target="_blank" id="ig"><i class="fab fa-instagram"></i></a>
                </li>
                {% else %}
                <li><a href="{{request.user.userdetails.Instagram}}" target="_blank" id="ig"><i
                            class="fab fa-instagram"></i></a></li>
                {% endif %}
                {% if not request.user.userdetails.Website %}
                <li><a href="https://www.google.com" target="_blank" id="ws"><i class="far fa-globe"></i></a></li>
                {% else %}
                <li><a href="{{request.user.userdetails.Website}}" target="_blank" id="ws"><i
                            class="far fa-globe"></i></a></li>
                {% endif %}
                {% if not request.user.userdetails.Mobile %}
                <li><a href="https://wa.me/" id="wa" target="_blank" rel="nofollow noopener"><i
                            class="fab fa-whatsapp"></i></a></li>
                {% else %}
                <li><a href="https://wa.me/{{request.user.userdetails.Mobile}}?text=Hi" id="wa" target="_blank"
                        rel="nofollow noopener"><i class="fab fa-whatsapp"></i></a></li>
                {% endif %}
            </ul>
        </div>
        <div class="some">
            <a href="{% url 'logout' %}" class="btn">Logout</a>
            <a href="{% url 'changepassword' %}" class="btn">Change Password</a>
        </div>
    </div>
    <div class="block">
        <div class="detailform">
            <form class="form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for f in fm %}

                <label for="">
                    <span class="label">{{f.label_tag}}</span>
                    {{f}}
                </label><br>
                {% endfor %}

                <label for="">
                    <input type="reset" value="reset">
                </label><br>

                <label for="">
                    <input type="submit" value="Save">
                </label><br>
            </form>
        </div>
    </div>
</section>

{% endblock body %}

{% block js %}
<script>
    let options = document.querySelectorAll('#id_User option');
    options.forEach((value, index) => {
        if (options[index].innerHTML == "{{request.user}}") {
            return;
        } else {
            options[index].style.display = 'none';
        }
    });

</script>
{% endblock js %}